name: tools
description: 我的常用工具包.
publish_to: 'none'
version: 1.0.7+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  process_run: ^0.12.3+2
  provider: ^6.0.2
  desktop_drop: 0.4.4
#  file_selector: ^0.8.4+1
  file_selector: 1.0.2
  shared_preferences: 2.2.2
  path_provider: 2.1.2
  dio: ^4.0.6
  archive: ^3.3.7
  event_bus: ^2.0.0
  substring_highlight: ^1.0.33
  flutter_list_view: 1.1.22
  dotted_border: ^2.0.0+2
  selector_plus:
    git: https://github.com/EaniaHuui/selector_plus.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  # xml解析
  xml: ^6.1.0
  # 加密解密
  crypto: ^3.0.2
  # 二维码
  qr_flutter: ^4.0.0
  helpers: 1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: IconFont
      fonts:
        - asset: fonts/iconfont.ttf
