name: tools
description: 我的常用工具包.
publish_to: 'none'
version: 1.0.7+1

environment:
  sdk: '>=3.1.0-333.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  process_run: 0.14.1+3
  provider: 6.1.1
  desktop_drop: 0.4.4
#  file_selector: ^0.8.4+1
  file_selector: 1.0.2
  shared_preferences: 2.2.2
  path_provider: 2.1.2
  dio: 5.4.0
  archive: 3.4.10
  event_bus: ^2.0.0 # 有两年没更新了
  substring_highlight: ^1.0.33 # 有两年没更新了
  flutter_list_view: 1.1.22
  dotted_border: 2.1.0
  selector_plus:
    git: https://github.com/EaniaHuui/selector_plus.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.6
  flutter_svg: 2.0.9
  # xml解析
  xml: 6.5.0
  # 加密解密
  crypto: 3.0.3
  # 二维码
  qr_flutter: 4.1.0
  helpers: 1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: IconFont
      fonts:
        - asset: fonts/iconfont.ttf
